### ISSUE TITLE
Asset location bug fix

### ISSUE THREAD

**Issue by vyx04** [vives-project-xp/EducationalGame1#101]
Het oplossen van een bug waarbij de locatie van een asset niet overeenkomt bij de verschillende window groottes.

**Comment by estebandesmedt** [comment]
Fixed location for HOUSE class (using OBJ inheritance class)

-TODO:
Fix this for all classes

! for classes without levels it doesn't work for the moment because you update self.images (image for each level) but classes with levels only have self.image

**Comment by estebandesmedt** [comment]
Fixed for all except:
ROAD
TREE
