### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by estebandesmedt** [vives-project-xp/EducationalGame1#16]
TODO: UML diagram maken van alle klassen die worden gebruikt.
Up to date houden van dit diagram bij veranderingen

**Comment by OlivierWesterman** [comment]
Wrote on the whiteboard what we have so far, needs to be cleaned up by Esteban.

Missing:
List of all attributes.
Game class (too big too fit on 1 white board)

**Comment by OlivierWesterman** [comment]
![image](https://github.com/vives-project-xp/EducationalGame1/assets/145467433/0c500212-bb86-4388-9700-decb278a2ebf)

**Comment by OlivierWesterman** [comment]
![image](https://github.com/vives-project-xp/EducationalGame1/assets/145467433/55b89603-8114-4259-b258-0bbbacb08e84)

**Comment by OlivierWesterman** [comment]
added the final version of the UML diagram to Documentation>Architecture and UML 
as well as in Game Documentation>
